research_task:
  description: >
    Research the provided chapter topic: {topic}, title {chapter_title}, and outline to gather additional content that will be helpful in writing the chapter.
    Ensure you focus on reliable, high-quality sources of information.

    Here is the outline description for the chapter: {chapter_description}

    When researching, consider the following key points:
    - you need to gather enough information to write up to 280 characters chapter
    - The chapter you are researching needs to fit in well with the rest of the chapters in the book.

    Here is the outline of the entire book:
    {post_outline}
    
    Here is the previous chapter content do not repeat it:
    {previous_chapter_content}
  expected_output: >
    A set of additional insights and information that can be used in writing the chapter.
  agent: researcher

writer_task:
  description: >
    Write a well-structured chapter based on the chapter title, goal, and outline description. 
    Each chapter should be written in plaintext and contains between 200 and 280 characters.

    Here is the topic for the book: {topic}
    Here is the title of the chapter: {chapter_title}
    Here is the outline description for the chapter: {chapter_description}

    Important notes:
    - The chapter you are writing needs to fit in well with the rest of the chapters in the book.

    Here is the outline of the entire book:
    {post_outline}

    Here is the previous chapter content, make sure to have consisten content across two chapters:\n\n
    {previous_chapter_content}
  expected_output: >
    A chapter content of around 280 characters that covers the provided chapter title and outline description
    also taking into consideration research for those.
  agent: writer
