research_task:
  description: >
    Conduct a thorough research about news and trending topics in science.
    Find different sources, websites and compile a list of the most relevant information.
    Make sure you find any interesting and relevant information given
    the current year is 2024.
  expected_output: >
    A list with at least 10 proposed topics from different websites
    with structure of title, description and exact url where it was taken from.
  agent: researcher
